services:
  nginx:
    restart: on-failure
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs:/etc/nginx/certs:ro
      - /etc/ssl/private:/etc/nginx/private:ro
    depends_on:
      - api
      - codehouse